-- Seeded from Case(4).docx test case library (19 rows)
CREATE TABLE IF NOT EXISTS scam_cases (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    source VARCHAR(512),
    url_link VARCHAR(512),
    scam_type VARCHAR(50) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    news_date DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_scam_cases_scam_type ON scam_cases(scam_type);
CREATE INDEX IF NOT EXISTS idx_scam_cases_platform ON scam_cases(platform);
CREATE INDEX IF NOT EXISTS idx_scam_cases_news_date ON scam_cases(news_date);

INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Elderly Woman Falls Victim To Online Part-time Job Offer, Loses Over RM500,000', 'A 71-year-old woman in Kuching lost RM527,130 after falling for a fraudulent part-time job offer sent by an unknown individual on TikTok. Lured by the promise of lucrative commissions, she completed "tasks" that required her to make 23 separate transactions to 16 different bank accounts. She only realized it was a scam when the promised returns never materialized. Kuching police revealed that 49 similar cases have been investigated since the start of the year, with total losses reaching RM2.26 million.', 'Bernama', 'https://www.bernama.com/en/news.php?id=2496938', 'JOB_SCAM', 'tiktok', DATE '2025-12-19'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Elderly Woman Falls Victim To Online Part-time Job Offer, Loses Over RM500,000');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Trader Loses Over RM500,000 To Online Job Scam', 'A 38-year-old trader in Kuala Terengganu lost over RM500,000 after being contacted by a Facebook user named "Nabila Puteri." He was lured by a part-time job offering high commissions. To "earn," he was instructed to buy items through a suspicious app. After an initial small commission was paid to gain his trust, he performed 38 more transactions to 22 different bank accounts using his life savings and credit cards.', 'Bernama', 'https://www.bernama.com/en/news.php?id=2443416', 'JOB_SCAM', 'facebook', DATE '2025-05-14'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Trader Loses Over RM500,000 To Online Job Scam');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Retired Engineer Loses Over RM100,000 In Scam Recovery Ruse', 'In a double-blow case, a retired engineer who had previously lost money to a scam fell for a second scam on Facebook. He clicked an ad promising to "recover lost scam money." The "recovery agents" on WhatsApp convinced him to pay "file opening fees" and "processing charges," leading to an additional loss of RM108,001 via 8 online transfers.', 'The Star', 'https://www.thestar.com.my/news/nation/2026/01/14/retired-engineer-loses-over-rm100000-in-scam-recovery-ruse', 'JOB_SCAM', 'facebook', DATE '2026-01-14'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Retired Engineer Loses Over RM100,000 In Scam Recovery Ruse');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Malaysian victim speaks of scam by ''friend'', torture in Cambodia', 'A 40-year-old businessman who escaped a job syndicate in Cambodia shared his ordeal. He was lured by a "friend" to Bangkok but was instead taken to a guarded hostel in Cambodia. He was forced to work for a scam center, calling people in Singapore and Malaysia to steal their IC numbers under the guise of being "cybersecurity officers."', 'The Straits Times', 'https://www.straitstimes.com/asia/se-asia/malaysian-victim-speaks-of-scam-by-friend-torture-in-cambodia', 'JOB_SCAM', 'facebook', DATE '2025-12-04'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Malaysian victim speaks of scam by ''friend'', torture in Cambodia');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Housewife Loses RM223,000 To Investment Scam', 'A 51-year-old housewife in Bentong was lured into a "non-existent investment scheme" that functioned like a part-time job. She made 12 transactions from her personal savings (including money left by her late husband) to seven different bank accounts before the bank alerted her that the recipients were flagged for fraud.', 'Bernama', 'https://bernama.com/en/news.php?id=2472976', 'JOB_SCAM', 'phone_call', DATE '2025-09-30'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Housewife Loses RM223,000 To Investment Scam');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Singapore Travellers To Malaysia Lose S$24,000 In Phishing Scams', 'Scammers sent SMS alerts to Malaysian and Singaporean travelers claiming unpaid road tolls. Victims clicked a link to a fake portal, entered their bank details, and lost a combined $24,000 (approx. RM80,000).', 'Bernama', NULL, 'phishing', 'whatsapp', DATE '2026-02-11'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Singapore Travellers To Malaysia Lose S$24,000 In Phishing Scams');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Phishing Scams Impersonating RMP', 'A widespread phishing campaign targeted Malaysian drivers by sending SMS alerts impersonating the Royal Malaysia Police (PDRM). The message claimed the recipient had "unpaid traffic summons" that would lead to legal action if not settled immediately.', 'Bernama / Singapore Police Force (Regional Alert)', NULL, 'phishing', 'whatsapp', DATE '2026-01-10'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Phishing Scams Impersonating RMP');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Malaysia scam losses rise to RM2.7bil in 2025, spike during festive seasons', 'During the 2026 Ramadan and Aidilfitri season, phishing activity spiked by 76%. Scammers distributed links via social media and WhatsApp promising “Government E-Duit Raya” subsidies or festive bonuses.', 'The Star', NULL, 'phishing', 'whatsapp', DATE '2026-03-24'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Malaysia scam losses rise to RM2.7bil in 2025, spike during festive seasons');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Beware! Impersonation Of The CEO Of EPF (Feb 12, 2026)', 'Scammers impersonated high-ranking Employees Provident Fund (EPF/KWSP) officials, including the CEO, by sending fraudulent emails and SMS claiming that a "security audit" or "identity synchronization" was mandatory to prevent i-Akaun suspension. Victims were lured into clicking a link to a fake EPF portal, where they unknowingly handed over their passwords and OTPs, allowing scammers to take control of their retirement savings data to change beneficiary details or attempt unauthorized withdrawals.', 'KWSP Official', NULL, 'phishing', 'whatsapp', DATE '2025-02-24'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Beware! Impersonation Of The CEO Of EPF (Feb 12, 2026)');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Be cautious of SCAMS involving Pos Malaysia!', 'Exploiting the high volume of online shopping, scammers sent SMS alerts claiming to be from Pos Malaysia. The message stated that a parcel could not be delivered due to an “incomplete address” or “missing house number”.', NULL, 'https://www.pos.com.my/scam-update', 'phishing', 'whatsapp', DATE '2025-01-09'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Be cautious of SCAMS involving Pos Malaysia!');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'QR Code Manipulation: Scammers'' New Tactic To Steal Users'' Data', 'Scammers targeted local food stalls and night markets by pasting their own fraudulent DuitNow QR stickers over the merchants'' original payment codes. Customers who scanned these manipulated codes to pay for their meals unknowingly transferred their money directly into the scammers'' bank accounts rather than to the vendors. PDRM issued a nationwide alert after dozens of merchants in Kuala Lumpur reported a sudden loss of daily earnings due to these physical QR overlays.', 'Bernama', NULL, 'qr_code_scam', 'phone_message', DATE '2025-01-09'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'QR Code Manipulation: Scammers'' New Tactic To Steal Users'' Data');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Manipulasi Kod QR Taktik Scammer Perangkap Pengguna', 'Exploiting the digital "Duit Raya" trend, scammers shared QR codes on WhatsApp promising a government-funded Aidilfitri subsidy of RM500. The scan led to a site that requested a "face scan" or biometric verification to unlock the funds, which was actually a tactic to steal the victim''s facial data and bypass banking security features. This case highlighted a new level of "Quishing" where scammers use QR codes to harvest biometric data for identity theft.', 'Bernama', NULL, 'qr_code_scam', 'whatsapp', DATE '2025-08-14'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Manipulasi Kod QR Taktik Scammer Perangkap Pengguna');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Careless QR Scanning Leads to Data Leaks and Financial Loss', 'At several Malaysian airports and malls, scammers placed QR code stickers on public charging stations promising "Free High-Speed Wi-Fi" for users who scanned them. Instead of providing internet access, the QR code redirected the browser to a page that forced the installation of a hidden "tracking profile" or spyware on the device. This allowed scammers to monitor the victim''s keystrokes and steal login credentials for social media and banking apps in real-time.', 'Bernama', NULL, 'qr_code_scam', 'whatsapp', DATE '2025-08-14'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Careless QR Scanning Leads to Data Leaks and Financial Loss');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Online scammer uses fake ID, QR code to take RM9,000', 'An insurance salesperson in Sibu lost nearly RM9,000 after being lured by a scammer offering a fake installment plan for a prize purchase. To gain her trust, the suspect used a fake employee ID card. The victim was then deceived into scanning a QR code that allowed the suspect to gain illegal access to her accounts. Once scanned, her savings were quickly drained through a series of rapid unauthorized transactions.', 'The Star', NULL, 'qr_code_scam', 'whatsapp', DATE '2026-02-20'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Online scammer uses fake ID, QR code to take RM9,000');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'New Scam Alert: Physical Red Packets with Fraudulent QR Codes', 'During the 2026 festive season, Maybank issued an emergency alert regarding physical "Lucky Packets" (Angpao) being distributed in public areas and mailboxes. These packets contained cards with QR codes promising "free lucky money" or "festive rewards." Scanning the code directed victims to a fake website that harvested banking credentials or prompted the download of malicious files, resulting in account takeovers.', 'Maybank2u', NULL, 'qr_code_scam', 'phone_message', DATE '2026-02-20'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'New Scam Alert: Physical Red Packets with Fraudulent QR Codes');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Two Company Directors In Penang Lose Nearly RM900,000 To Phone Scams', 'A 69-year-old retired clerk in Penang lost RM457,607 after receiving a call from a scammer impersonating an officer from the Malaysian Communications and Multimedia Commission (MCMC). The victim was told her phone number was involved in illegal activities and was coerced into "registering" her bank account for an audit by providing her online banking credentials and multiple OTP/TAC codes. These codes allowed the scammers to gain full control of her account and perform 11 unauthorized transfers within a single afternoon.', 'Bernama', NULL, 'otp_scam', 'whatsapp', DATE '2026-03-27'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Two Company Directors In Penang Lose Nearly RM900,000 To Phone Scams');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Medical Specialist Loses RM529,200 To Non-Existent Investment Scam', 'A medical specialist in his 50s lost RM529,200 after being contacted by a scammer posing as a "legal assistant" from a reputable bank. The scammer claimed to be helping the specialist recover funds lost in a previous failed investment. To "verify the refund process," the victim was asked to provide his banking username and the OTP codes that arrived on his phone; instead of receiving a refund, his remaining life savings were systematically drained.', 'Bernama', NULL, 'otp_scam', 'tiktok', DATE '2026-01-03'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Medical Specialist Loses RM529,200 To Non-Existent Investment Scam');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Three Malaysians Detained In Online Scam, 46 Sim Cards Seized', 'PDRM arrested three individuals for a "SIM Swap" syndicate that targeted users of major Malaysian telcos like Maxis and Celcom. Scammers called victims pretending to be technical support, claiming their 4G SIM cards needed a "5G upgrade" to avoid service disruption. They asked the victims to read out a verification code sent via SMS; this code was actually the authorization to port the phone number to a new SIM card, allowing the scammers to intercept all future banking OTPs.', 'Bernama', NULL, 'otp_scam', 'whatsapp', DATE '2026-01-27'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Three Malaysians Detained In Online Scam, 46 Sim Cards Seized');
INSERT INTO scam_cases (title, content, source, url_link, scam_type, platform, news_date)
SELECT 'Selangor Police Deny Raya Fundraising Event, Confirm Scam Attempt', 'Selangor police warned the public about a viral SMS soliciting donations for a fake "PDRM Hari Raya Event." The message asked people to click a link to donate and then enter their OTP to "verify the charity contribution." Police confirmed that this was a phishing attempt where scammers harvested OTPs to gain access to the victims'' online banking portals under the guise of a charitable act.', 'Bernama', NULL, 'otp_scam', 'whatsapp', DATE '2026-03-25'
WHERE NOT EXISTS (SELECT 1 FROM scam_cases WHERE title = 'Selangor Police Deny Raya Fundraising Event, Confirm Scam Attempt');
