services:
  # 1. The Database (Using pgvector for AI capability)
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "127.0.0.1:5432:5432" # Securely bind to the server's internal localhost only
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_SHARED_BUFFERS: 2GB # Tell Postgres to use the RAM you gave it
    volumes:
      - ./data_persistence/postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres:/docker-entrypoint-initdb.d:ro
    # Cap db resource usage to avoid hanging
    blkio_config:
      device_write_bps:
        - path: /dev/sda
          rate: 10mb
      device_write_iops:
        - path: /dev/sda
          rate: 400
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 6G          # Buffer caching
        reservations:
          memory: 4G
    # Much faster db population, but dangerous (data corruption) if it crashes!
    command: postgres -c fsync=off -c synchronous_commit=off 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. The FastAPI Backend
  backend:
    build:
      context: ./backend # Tells Docker the 'root' for this build is the backend folder
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app # Mount the actual backend folder
      - ./data_persistence:/app/data_persistence #
      - /app/.venv # PROTECT: Use the container's internal Linux venv
    environment:
      OMP_NUM_THREADS: 1  # Force each process to use only 1 core
      MKL_NUM_THREADS: 1
      PYTHONUNBUFFERED: 1
      # We use the 'db' service name as the hostname
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME} # Tortoise needs postgres not postgresql
      MODEL_PATH: /app/models/huggingface
      OCI_PAR_URL: ${OCI_PAR_URL} 
      PERSISTENCE_PATH: /app/data_persistence
    # Nginx makes this unnecessary on oracle server, but it's helpful on local
    # We just block port 8000 on oracle.
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2.5'      # Never let the backend take more than 2 cores
          memory: 16G       # Primary need for RAM
        reservations: # Guarantees this amount is always available
          memory: 8G

  # 3. The React Frontend
  frontend:
    build: ./frontend
    restart: always
    # Uncomment only to test without Nginx
    ports:
      - "3000:80" # Maps React (Nginx port 80) to server port 3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # "Anonymous volume" - hides host node_modules and uses container's
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro # nginx config
    deploy:
      resources:
        limits:
          cpus: '0.5'      
          memory: 1024M       # Frontend doesn't need much

  # 4. Nginx Proxy Manager (SSL/DuckDNS "Manager")
  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    depends_on:
      frontend:
        condition: service_started # Wait for frontend before running
    restart: always
    ports:
      - "80:80" # Public HTTP
      - "81:81" # Management UI (Used to set up DuckDNS)
      - "443:443" # Public HTTPS
    volumes:
      - ./data_persistence/npm_data:/data
      - ./data_persistence/npm_letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  backend_packages: # Defines the persistent "storage bin"


