services:
  # 1. The Database (Using pgvector for AI capability)
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "127.0.0.1:5432:5432" # Securely bind to the server's internal localhost only
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. The FastAPI Backend
  backend:
    build:
      context: ./backend # Tells Docker the 'root' for this build is the backend folder
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ai_models:/app/models # The model lives here on the server
      - ./backend:/app # Mount the actual backend folder
      - /app/.venv # PROTECT: Use the container's internal Linux venv
    environment:
      # We use the 'db' service name as the hostname
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME} # Tortoise needs postgres not postgresql
      MODEL_PATH: /app/models/huggingface
    # Nginx makes this unnecessary on oracle server, but it's helpful on local
    # We just block port 8000 on oracle.
    ports:
      - "8000:8000"

  # 3. The React Frontend
  frontend:
    build: ./frontend
    restart: always
    # Uncomment only to test without Nginx
    ports:
      - "3000:80" # Maps React (Nginx port 80) to server port 3000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules # "Anonymous volume" - hides host node_modules and uses container's
    mem_limit: 2048m

  # 4. Nginx Proxy Manager (SSL/DuckDNS "Manager")
  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    ports:
      - "80:80" # Public HTTP
      - "81:81" # Management UI (Used to set up DuckDNS)
      - "443:443" # Public HTTPS
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  backend_packages: # Defines the persistent "storage bin"
