[project]
name = "askvigil-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aerich>=0.9.2",
    "asyncpg>=0.31.0",
    "fastapi>=0.135.2",
    "pydantic-settings>=2.13.1",
    "python-multipart>=0.0.22",
    "tortoise-orm>=0.25.4",
    "tortoise-vector>=0.2.0",
    "uvicorn>=0.42.0",
    "opencv-python-headless>=4.13.0.92",
    "torch>=2.11.0",
    "urlextract>=1.9.0",
    "httpx>=0.28.1",
    "ffmpeg-python>=0.2.0",
    "optimum[onnxruntime]>=2.1.0",
    "onnxruntime>=1.24.4",
    "easyocr>=1.7.2",
    "torchvision>=0.26.0",
    "onnx>=1.21.0",
    "onnxscript>=0.6.2",
    "pandas>=3.0.2",
    "scikit-learn>=1.8.0",
]

[tool.aerich]
tortoise_orm = "app.core.database.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.uv]
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]

[tool.uv.sources]
# Tell uv to prefer the CPU index for ALL platforms to ensure stability
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
xplicit = true
