name: Deploy to Oracle Cloud
on:
  push:
    branches: [main]
    paths-ignore:
      - ".devcontainer/**"
      - ".gitignore"
      - "README.md"
      - "docs/**"
jobs:
  deploy:
    needs: lint-and-fix
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. The SSH URL for the repo
            REPO_URL="git@github.com:${{ github.repository }}.git"
            TARGET_DIR="~/AskVigil"

            # 2. First-time setup: If the folder doesn't exist, clone it
            if [ ! -d "$TARGET_DIR/.git" ]; then
              echo "🚀 Initializing private repository..."
              git clone $REPO_URL $TARGET_DIR
            fi

            cd $TARGET_DIR

            # 3. Clean Slate: Fetch latest ver and auto-lint fixes to force the server to match GitHub exactly.
            git fetch origin main
            git reset --hard origin/main

            # 4. Deploy
            docker compose -f docker-compose.yml up -d --build
